### PR TITLE
Honour stack.yaml's subdirs

### LINKED ISSUE #30: Fails on `subdirs` of location.
I have a repository with multiple packages in it (mega repo). I want to use packages from it. In stack this is expressible by

```
- location:
    git: giturl
    commit: gitrev
  subdirs:
    - package1
    - package2
```

https://docs.haskellstack.org/en/stable/yaml_configuration/#complex-package-locations-location

However on such a setup, stackage2nix fails through cabal2nix:

`*** found zero or more than one cabal file ([]). Exiting.`

### PR DESCRIPTION
**Pull request by Fuuzetsu**
Closes #30.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
Sorry, this is not enough as expressions generated still only refer to the git repository, without the subdirectory. Let me figure out how to deal with that. I'll also fix test compile.

**Comment by Fuuzetsu** [comment]
I have amended the commit. It now inserts `postUnpack` just like cabal2nix does as appropriate. The tests should be fixed as well.

**Comment by 4e6** [comment]
Looks good, thank you! What's up with `postUnpack`?

**Comment by 4e6** [comment]
Oh, you were talking about new `subpath` attribute. Nevermind

**Pull request merged**
